export { default as Body } from './Body'
export { default as Caption } from './Caption'
export { default as Display } from './Display'
export { default as Headline } from './Headline'
export { default as Label } from './Label'
export { default as Title } from './Title'